name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make compile xref dialyzer

    - name: Get elvis
      uses: actions/checkout@v2
      with:
        repository: inaka/elvis
        path: elvis
    - name: Build elvis
      run: rebar3 escriptize
        working-directory: elvis
    - name: Run elvis
      run: |
        elvis/_build/default/bin/elvis rock

    - name: Run tests
      run: make test
